### ISSUE TITLE
Enhance discovery.js to account for unit test restructuring

### ISSUE THREAD

**Issue by akudev** [SAP/connect-openui5#26]
As the UI5 core unit tests are being changed to no longer have an HTML page on their own, it has become difficult to run them: 
One has at least to manually construct the testsuite URL like http://localhost:8080/testsuite/test-resources/sap/ui/core/qunit/generic/testsuite.generic.qunit.html (or bookmark ONE testsuite URL and manually adapt to get to the currently needed testsuite). Then the start of the tests has to be interrupted and the actual test link has to be opened. At least that's the best way I know so far.

Proposal: in discovery.js also loop over all found testsuite(.*).qunit.js files, extract the information about all contained tests, and add these tests just like regular HTML pages to the testsuite's left-hand tree.
The file could be displayed as [testname].qunit.js and the URL could be
...Test.qunit.html?testsuite=[found testsuite file]&test=[testname]

I quickly tried doing it myself, but encountered the following challenges:

- How to get from the "virtual" testsuite file name to a physical file that can be loaded? (probably a no-brainer for domain experts)
- testsuite.qunit.js files are not simply JSON files, but contain JS code which starts with the sap.ui.define(...) function, which is not defined in the node environment (could be defined to return the contained test configuration)

So all in all it might be easy to achieve and would restore ease of access for the tests.

**Comment by matz3** [comment]
I think in general this should be achievable with a certain amount of effort.
In order to also support the Java / Tomcat based development setup, this would also need to be changed in there: https://github.com/SAP/openui5/blob/master/src/testsuite-utils/src/main/java/com/sap/openui5/DiscoveryService.java

There is also an internal implementation of this service which needs to be adopted as well.

**Comment by matz3** [comment]
This project has been deprecated (see https://github.com/SAP/connect-openui5/pull/222)
